### ISSUE TITLE
variable.state doesn't work

### ISSUE THREAD

**Issue by OleksandrBerchenko** [rogro82/hass-variables#14]
According to documentation, the following statement should work inside "variable.set_variable" block:

```{{ variable.state }}```

In fact, it doesn't.  I have the following script:

```
test_variable:
  sequence:
    - service: variable.set_variable
      data_template:
        variable: logitech_input
        value_template: "{{ variable.state + 1 }}"
```

It crashes with the following error in the log:

```Error rendering data template: UndefinedError: 'variable' is undefined```

```{{ states.variable.logitech_input.state }}``` works fine.

To be honest, I don't think it's a crucial functionality, because ```states.variable...``` may be used instead, so possibly it makes sense just to remove it from documentation.

See also https://github.com/rogro82/hass-variables/issues/12 .

Thanks!
