### ISSUE TITLE
Can't set value from scene

### ISSUE THREAD

**Issue by infernix** [rogro82/hass-variables#2]
Hi,

Variable definition:
```
variable:
 setpoint_temperature_living:
  value: 18
  restore: true
  attributes:
          friendly_name: 'Setpoint Temperature Living'
```

Scene:
```
- name: "Climate: sleeping"
  entities:
    variable.setpoint_temperature_living:
      value: 20
```

When trying to activate this scene, HASS logs:
` hass[20221]: #033[33m2018-01-10 19:33:29 WARNING (MainThread) [homeassistant.helpers.state] reproduce_state: Unable to reproduce state <state variable.setpoint_temperature_living=None; value=20 @ 2018-01-10T19:33:16.193756+01:00> (2)#033[0m`

Is this not supported?
