### ISSUE TITLE
Use custom Unit_of_measurement with variable

### ISSUE THREAD

**Issue by georg90** [rogro82/hass-variables#22]
I use the variables to feed data into Home assistant from local sensors and different apis. For example I have a temperature / humidity sensor, which is updating two variables when it gets an update.

However, I want to show the unit in the UI. How can I set a unit of the variable in use?

I have this:
![grafik](https://user-images.githubusercontent.com/6489464/57010267-1df46f80-6bfc-11e9-95f7-0a9b0ee7e1a9.png)

I want this (shot from other SH system):
![grafik](https://user-images.githubusercontent.com/6489464/57010241-09b07280-6bfc-11e9-9eab-265299ddabdb.png)

**Comment by OleksandrBerchenko** [comment]
I don't think it's possible to assign a unit of measurement to a variable (treat it like a usual "variable" in a programming language), but you can setup a sensor like:

```
sensor:
  - platform: template
    sensors:
      temperature:
        value_template: "{{ states('variable.temperature') }}"
        unit_of_measurement: '°C'
\
```
