### ISSUE TITLE
can't set variable to value_template using trigger.to_state.attributes.friendly_name 

### ISSUE THREAD

**Issue by kiwijunglist** [rogro82/hass-variables#4]
value_template for either
- trigger.to_state.attributes.friendly_name 
- trigger.to_state.name

Doesn't work.

In the example automation below, the notification will show trigger.to_state.attributes.friendly_name however the variable doesn't get set to trigger.to_state.attributes.friendly_name 

```
- alias: "01 First trigger"
  trigger:
    - platform: state # Door and window
      entity_id: binary_sensor.door_window_sensor_158d0001d63b07, binary_sensor.door_window_sensor_158d0001ef77d8, binary_sensor.door_window_sensor_158d0001fa792d, binary_sensor.door_window_sensor_158d0001a94c35, binary_sensor.door_window_sensor_158d0001f9e2e2, binary_sensor.door_window_sensor_158d0001f38b1f
      from: 'off'
      to: 'on'
    - platform: state # Motion
      entity_id: binary_sensor.motion_sensor_158d0001e57659, binary_sensor.motion_sensor_158d0001e52dee, binary_sensor.motion_sensor_158d0001dc7526
      from: 'off'
      to: 'on'
  action:
    - service: timer.start
      entity_id: timer.alarm_triggered
    - service: variable.set_variable
      data:
        variable: alarm_triggerone
        value_template: '{{ trigger.to_state.attributes.friendly_name }}'
    - service: notify.html5
      data_template:
        message: 'Alarm has been tripped by  {{ trigger.to_state.attributes.friendly_name }}'
      data:
        data:
          tag: 'notification-about-sensor'
```

**Comment by kiwijunglist** [comment]
PS - thanks for your variable custom component, I am using it with a some custom "meta sensors".

**Comment by rogro82** [comment]
You should use data_template to access the trigger property instead of data and then set value

```
- service: variable.set_variable
      data_template:
        variable: alarm_triggerone
        value: '{{ trigger.to_state.attributes.friendly_name }}'
```

**Comment by SquareBeard** [comment]
And how do you access the `variable` object when using both data_template and value_template ?

This does not work:
```
- service: variable.set_variable
  data_template:
    variable: test
    value_template: '{{ variable.state + trigger.payload }}'
```

**Comment by SquareBeard** [comment]
Nevermind, this works:
```
- service: variable.set_variable
  data_template:
    variable: test
    value_template: '{{ "{{ variable.state }}" + trigger.payload }}'
```
