### ISSUE TITLE
How can I delete an attribute?

### ISSUE THREAD

**Issue by JeeCee1** [rogro82/hass-variables#42]
Sorry if I've read over it, but I can't find a way to delete an added attribute.

Thanks for your efforts and help!

**Comment by makp0** [comment]
Hello.
It happens to my setup too.
Furthermore, if I delete variable and then re-add it, Hassio seems to add the old configuration of it.
For example, if initial variable is of type boolean than re-adding it as integer seems to have no effect as it still holds boolean as well as an attribute which doesn't exist in the configuration anymore.

Current config:
```
variable:
  dustbin_full:
    value: 0
    restore: true
```
Previous config:
```
variable:
  dustbin_full:
    value: False
    attributes:
      previous: 0
    restore: true

```
Variable states export from DB:
[states-export.zip](https://github.com/rogro82/hass-variables/files/5155016/states-export.zip)
