### ISSUE TITLE
Question: Template inside a variable

### ISSUE THREAD

**Issue by poudenes** [rogro82/hass-variables#46]
Hi All, 

Is it possible to do something like this:

```
adaptive_kelvin:
    value: "{{ states.switch.adaptive_lighting_sensor.attributes.color_temp_kelvin | round(0)}}"
    attributes:
      friendly_name: 'Adaptive Kelvin'
      icon: mdi:theme-light-dark
```
And use this variable "adaptive_kelvin" into automation? something like this:

```
- service: light.turn_on
   data:
     entity_id: light.livingroom_all
     brightness_pct: 100
     kelvin: "{{ [variable.adaptive_kelvin] }}"
```

kind regards,
