### ISSUE TITLE
variable, attributes_template does not work

### ISSUE THREAD

**Issue by gribouk** [rogro82/hass-variables#53]
Dear All,

I am trying to use variable objects for my project, but the attributes_template do not work for some reason. I made a small example which yelds no result and I fail to understand why:

```
    detectors_list:
        value: 0
        attributes:
            list: "binary_sensor.dining1"

this I call from developer's tools, services, variable.set_variable with data below

variable: detectors_list
value_template: 2
attributes: >  
  { 
    "list": "{{ variable.attributes.list }}" 
  }
```

No metter what I try, the attributes do not change. Would anyone give me a hint why?

The error message from the log:

Logger: homeassistant
Source: custom_components/variable/__init__.py:219
First occurred: 23:57:58 (1 occurrences)
Last logged: 23:57:58

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/variable/__init__.py", line 219, in async_set_variable
    attributes = json.loads(
  File "/usr/local/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not Wrapper
