### ISSUE TITLE
Can't read variable in automation conditions.

### ISSUE THREAD

**Issue by komw** [rogro82/hass-variables#6]
There is no possible to use variables as a conditions in automation like:
```
variable:
  heating_off_set_by_automation:
    name: heating_off_set_by_automation
    value: False
automation:
  - alias: turn off
    trigger:
      platform: time
      seconds: '/5'
    condition:
      - condition: template
        value_template: '{{ variables.heating_off_set_by_automation == False }}'
    action:
      - service: switch.turn_on
        entity_id: switch.heating_force_turn_off
```
