### ISSUE TITLE
Dosen't work after update HA to 2022.7.x

### ISSUE THREAD

**Issue by YvesZH** [rogro82/hass-variables#63]
after homeassistant update from 2022.6.x to 2022.7.x your super tool doesn't seem to work anymore

**My Automation:**

```
  - id: 'katze_wurde_gefuettert_copy_to_variable'
    alias: 'katze_wurde_gefuettert_copy_to_variable' 
    trigger: 
      platform: state 
      entity_id: binary_sensor.katzenfutter_aqara_vibra_c
      to: 'on'
    action:
      - delay: 00:00:01
      - service: variable.set_variable
        data:
          variable: letztes_mal_katze_gefuettert
          value_template: '{{ states.binary_sensor.katzenfutter_aqara_vibra_c.last_changed }}'
```

**Automation debugging:**

![C12D22D8-6233-4B00-94F9-E015C7109735](https://user-images.githubusercontent.com/64573990/178134097-eeff4b48-6275-4c7c-836b-47d0afdb436c.jpeg)
![42D428E8-5EBA-41E2-A3DD-594D759A9372](https://user-images.githubusercontent.com/64573990/178134098-eb5d64d8-acce-4d1c-bae2-0dcd44ca2bd9.jpeg)

**HA-Log:**
Logger: homeassistant.components.automation.katze_wurde_gefuettert_copy_to_variable
Source: custom_components/variable/__init__.py:126 
Integration: Automatisierung ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22)) 
First occurred: 9. Juli 2022, 21:18:03 (2 occurrences) 
Last logged: 9. Juli 2022, 21:18:03

katze_wurde_gefuettert_copy_to_variable: Error executing script. Unexpected error for call_service at pos 2: wait() got an unexpected keyword argument 'loop'
While executing automation automation.katze_wurde_gefuettert_copy_to_variable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/variable/__init__.py", line 126, in async_set_variable_service
    yield from asyncio.wait(tasks, loop=hass.loop)
TypeError: wait() got an unexpected keyword argument 'loop'
