### ISSUE TITLE
Unable to find service variable.set_variable 

### ISSUE THREAD

**Issue by Bram-diederik** [rogro82/hass-variables#64]
I followed https://community.home-assistant.io/t/tts-to-media-player-and-resume-stream/128092 the MPD part.

and did the configuration on this readme. 

I have the varables set in the configuration but i get the error Unable to find service variable.set_variable when i run the script,

I think im doing something wrong but i cant find help else where. 

```
variable:
  mpdstream:
    value: 0
    attributes:
      icon: mdi:volume-high
  mpdcheck:
    value: 0
  ttssay:
    value: 0
```
