### ISSUE TITLE
use values for RGB setting

### ISSUE THREAD

**Issue by lengyej** [rogro82/hass-variables#7]
How can I use variables to set gateway RGB color?
What need I write to   "**rgb_color: [255,255,100]**" instead the numbers?
thanks!

Config:
variable:
  red_color:
    value: 50
  green_color: 
    value: 255
  blue_color:
    value: 50  

Automation:
: 
 action:
    - service: light.turn_on
      entity_id: light.gateway_light
      data:
        brightness: 4
        rgb_color: [255,255,100]

**Comment by OleksandrBerchenko** [comment]
This should work:

```
  - service: light.turn_on
    entity_id: light.gateway_light
    data_template:
      brightness: 4
      rgb_color: ["{{ states.variable.red_color.state | int }}", "{{ states.variable.green_color.state | int }}", "{{ states.variable.blue_color.state | int }}"]

```
